Update tsql-pr.yml

diff --git a/.github/workflows/tsql-pr.yml b/.github/workflows/tsql-pr.yml
--- a/.github/workflows/tsql-pr.yml
+++ b/.github/workflows/tsql-pr.yml
@@ -5,17 +5,32 @@ on:
     branches:
     - main
     paths:
-    - '**.sql'
-  push:
-    branches:
-    - main
+    - '*/DDL.sql'
+    - '*/DML.sql'
+    - '*/DQL.sql'
+  workflow_dispatch:
 
 jobs:
-  install-sql-server:
+  validate-tsql:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
+    - name: Check for required sql files
+      run: |
+        if ! [ -f sql/DDL.sql ]; then
+            echo "DDL.sql not found"
+            exit 1
+          fi
+          if ! [ -f sql/DML.sql ]; then
+            echo "DML.sql not found"
+            exit 1
+          fi
+          if ! [ -f sql/DQL.sql ]; then
+            echo "DQL.sql not found"
+            exit 1
+          fi
+          echo "All SQL files found"
     - name: Start SQL Server container
       run: |
         docker run -d \
@@ -28,8 +43,9 @@ jobs:
       run: sleep 30
     - name: Run T-SQL script
       run: |
-        for file in $(find . -name '*.sql');
-        do
-          echo "Executing $file..."
-          sqlcmd -S localhost -U SA -P 'Passw0rd11!' -b -i $file
-        done
+        echo "Executing DDL.sql file..."
+        sqlcmd -S localhost -U SA -P 'Passw0rd11!' -b -i sql/DDL.sql
+        echo "Executing DML.sql file..."
+        sqlcmd -S localhost -U SA -P 'Passw0rd11!' -b -i sql/DML.sql
+        echo "Executing DQL.sql file..."
+        sqlcmd -S localhost -U SA -P 'Passw0rd11!' -b -i sql/DQL.sql
